// Get all profiles
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_RESET = 'PROFILE_RESET';

// Get Single full-Profile by ID
export const PROFILE_BY_ID_REQUEST = 'PROFILE_BY_ID_REQUEST';
export const PROFILE_BY_ID_SUCCESS = 'PROFILE_BY_ID_SUCCESS';
export const PROFILE_BY_ID_FAILURE = 'PROFILE_BY_ID_FAILURE';
export const PROFILE_BY_ID_RESET = 'PROFILE_BY_ID_RESET';
