export const USER_REVIEW_LOGIN_REQUEST = 'USER_REVIEW_LOGIN_REQUEST';
export const USER_REVIEW_LOGIN_SUCCESS = 'USER_REVIEW_LOGIN_SUCCESS';
export const USER_REVIEW_LOGIN_FAILURE = 'USER_REVIEW_LOGIN_FAILURE';
export const USER_REVIEW_LOGOUT = 'USER_LOGOUT';

export const USER_REVIEW_ID_REQUEST = 'USER_REVIEW_ID_REQUEST';
export const USER_REVIEW_ID_SUCCESS = 'USER_REVIEW_ID_SUCCESS';
export const USER_REVIEW_ID_FAILURE = 'USER_REVIEW_ID_FAILURE';
