export const USER_REVIEW_LOGIN_REQUEST = 'USER_REVIEW_LOGIN_REQUEST';
export const USER_REVIEW_LOGIN_SUCCESS = 'USER_REVIEW_LOGIN_SUCCESS';
export const USER_REVIEW_LOGIN_FAILURE = 'USER_REVIEW_LOGIN_FAILURE';
export const USER_REVIEW_LOGOUT = 'USER_REVIEW_LOGOUT';

export const USER_REVIEWER_REGISTER_REQUEST = 'USER_REVIEWER_REGISTER_REQUEST';
export const USER_REVIEWER_REGISTER_SUCCESS = 'USER_REVIEWER_REGISTER_SUCCESS';
export const USER_REVIEWER_REGISTER_FAILURE = 'USER_REVIEWER_REGISTER_FAILURE';

export const USER_REVIEW_ID_REQUEST = 'USER_REVIEW_ID_REQUEST';
export const USER_REVIEW_ID_SUCCESS = 'USER_REVIEW_ID_SUCCESS';
export const USER_REVIEW_ID_FAILURE = 'USER_REVIEW_ID_FAILURE';

export const USER_REVIEW_CREATE_COMMENT_REQUEST =
  'USER_REVIEW_CREATE_COMMENT_REQUEST';
export const USER_REVIEW_CREATE_COMMENT_SUCCESS =
  'USER_REVIEW_CREATE_COMMENT_SUCCESS';
export const USER_REVIEW_CREATE_COMMENT_FAILURE =
  'USER_REVIEW_CREATE_COMMENT_FAILURE';
export const USER_REVIEW_CREATE_COMMENT_RESET =
  'USER_REVIEW_CREATE_COMMENT_RESET';
